services:
  env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  sql-server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQL_SERVER_PASSWORD}"
    expose:
      - "1433"
    volumes:
      - type: "volume"
        target: "/var/opt/mssql"
        source: "sql-server"
        read_only: false
    networks:
      - "aspire"
  webapp:
    image: "${WEBAPP_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${WEBAPP_PORT}"
      ConnectionStrings__what-you-did: "Server=sql-server,1433;User ID=sa;Password=${SQL_SERVER_PASSWORD};TrustServerCertificate=true;Initial Catalog=what-you-did"
      WHAT_YOU_DID_HOST: "sql-server"
      WHAT_YOU_DID_PORT: "1433"
      WHAT_YOU_DID_USERNAME: "sa"
      WHAT_YOU_DID_PASSWORD: "${SQL_SERVER_PASSWORD}"
      WHAT_YOU_DID_URI: "mssql://sa:${SQL_SERVER_PASSWORD}@sql-server:1433/what-you-did"
      WHAT_YOU_DID_JDBCCONNECTIONSTRING: "jdbc:sqlserver://sql-server:1433;trustServerCertificate=true;databaseName=what-you-did"
      WHAT_YOU_DID_DATABASENAME: "what-you-did"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "webapp"
    expose:
      - "${WEBAPP_PORT}"
    depends_on:
      sql-server:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  sql-server:
    driver: "local"
